version: '3.8'

services:
  web:
      build:
        context: angular_bankdash
        target: builder
      ports:
        - 4200:4200
      volumes:
        - ./angular_bankdash:/angular_bankdash
        - /angular_bankdash/node_modules

